---
- name: GET BGP SUMMARY
  hosts: prod
  gather_facts: false

  tasks:
    - name: SHOW BGP ALL
      block:
        - name: SHOW IP BGP SUMMARY
          arista.eos.eos_command:
            commands:
              - show ip bgp summary
            wait_for:
              - result[0] contains 'Estab'
      rescue:
        - name: Crush
          ansible.builtin.fail:
            msg: BGP state down.
